// Generated by CoffeeScript 1.7.1
(function() {
  var Lastfm, document, location, navigator, root,
    __hasProp = {}.hasOwnProperty;

  root = this;

  document = root.document;

  navigator = root.navigator;

  location = root.location;

  Lastfm = (function() {
    function Lastfm(options) {
      this.apiProtocol = "http";
      this.apiUrl = "ws.audioscrobbler.com";
      this.apiVersion = "2.0";
      this.apiBaseUrl = this._constructApiBaseUrl(this.apiProtocol, this.apiUrl, this.apiVersion);
      this.key = options.key, this.format = options.format;
      this.format = this.format || "json";
    }

    Lastfm.prototype.artistGetInfo = function(artist, callback) {
      return this._apiRequest("artist.getinfo", {
        artist: artist
      }, callback);
    };

    Lastfm.prototype._apiRequest = function(method, params, callback) {
      var param, request, requestString, url;
      requestString = "";
      for (param in params) {
        if (!__hasProp.call(params, param)) continue;
        request = params[param];
        requestString += "&" + param + "=" + (encodeURIComponent(request));
      }
      url = "" + this.apiBaseUrl + "?method=" + method + requestString + "&api_key=" + this.key + "&format=" + this.format;
      return this._xhrRequest(url, callback);
    };

    Lastfm.prototype._constructApiBaseUrl = function(protocol, url, version) {
      return this.apiBaseUrl = "" + protocol + "://" + url + "/" + version + "/";
    };

    Lastfm.prototype._xhrRequest = function(url, callback) {
      var xhr;
      xhr = new XMLHttpRequest();
      xhr.onreadystatechange = function() {
        var response;
        if (xhr.readyState === 4 && xhr.status === 200) {
          response = JSON.parse(xhr.responseText);
          return callback(response);
        }
      };
      xhr.open("GET", url, true);
      return xhr.send();
    };

    return Lastfm;

  })();

  if ((typeof define !== "undefined" && define !== null ? define.amd : void 0) != null) {
    define([], function() {
      return Lastfm;
    });
  } else {
    root.Lastfm = Lastfm;
  }

}).call(this);

//# sourceMappingURL=lastfm.map
