// Generated by CoffeeScript 1.7.1
(function() {
  var Nravasada, document, location, navigator, root;

  root = this;

  document = root.document;

  navigator = root.navigator;

  location = root.location;

  Nravasada = (function() {
    function Nravasada(options) {
      this.url = options.url, this.imageNode = options.imageNode, this.lastfm = options.lastfm;
      this._overloadPutMetadata();
      this._injectScript();
      setInterval((function(_this) {
        return function() {
          console.log("Update");
          return _this._injectScript();
        };
      })(this), 5000);
    }

    Nravasada.prototype._overloadPutMetadata = function() {
      var proxiedPutMetadata;
      proxiedPutMetadata = window.PutMetadata;
      if (!window.PutListeners) {
        window.PutListeners = function() {};
      }
      return window.PutMetadata = (function(_this) {
        return function(radioname, djnick, djid, djchat, song) {
          var artist;
          _this.radioname = radioname;
          _this.djnick = djnick;
          _this.djid = djid;
          _this.djchat = djchat;
          artist = song.split("-")[0];
          if (_this.artist !== artist) {
            _this.artist = artist;
            _this._getCover(_this.artist);
          }
          if (proxiedPutMetadata) {
            return proxiedPutMetadata.apply(_this, arguments);
          }
        };
      })(this);
    };

    Nravasada.prototype._injectScript = function() {
      return document.head.appendChild(this._composeScriptNode());
    };

    Nravasada.prototype._composeScriptNode = function() {
      this.script = document.createElement("script");
      this.script.src = this.url;
      return this.script;
    };

    Nravasada.prototype._getCover = function(artist) {
      return this.lastfm.artistGetInfo(artist, (function(_this) {
        return function(response) {
          if ((response != null ? response.artist : void 0) != null) {
            _this.imageSrc = response.artist.image[4]["#text"];
            return _this._updateImage();
          }
        };
      })(this));
    };

    Nravasada.prototype._updateImage = function() {
      return this.imageNode.style.backgroundImage = "url(" + this.imageSrc + ")";
    };

    return Nravasada;

  })();

  if ((typeof define !== "undefined" && define !== null ? define.amd : void 0) != null) {
    define([], function() {
      return Nravasada;
    });
  } else {
    root.Nravasada = Nravasada;
  }

}).call(this);

//# sourceMappingURL=nravasada.map
